#!/usr/bin/env node
// Examples are maintained in examples/examples.js. C++ files exist only in ignored build output;
// the Operations and Programs pages of docs/ are generated from them with --docs.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {examples, sourceOf, operationOf} from '../examples/examples.js';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const docs = path.join(root, 'docs'), images = path.join(docs, 'images/examples');
const hash = item => createHash('sha256').update(sourceOf(item)).digest('hex');
// Example source alone misses changes to defaults, CPU planning and WGSL kernels.
// Conservatively invalidate the gallery when any library/build input changes.
const implementationHash = () => {
  const files = ['CMakeLists.txt'];
  const visit = directory => {
    for (const entry of fs.readdirSync(path.join(root, directory), {withFileTypes: true})) {
      const name = `${directory}/${entry.name}`;
      if (entry.isDirectory()) visit(name);
      else if (entry.isFile()) files.push(name);
    }
  };
  for (const directory of ['include', 'src', 'cmake']) visit(directory);
  const digest = createHash('sha256');
  for (const file of files.sort()) {
    digest.update(file).update('\0').update(fs.readFileSync(path.join(root, file))).update('\0');
  }
  return digest.digest('hex');
};
const write = (file, data) => {
  if (!fs.existsSync(file) || fs.readFileSync(file,'utf8') !== data) fs.writeFileSync(file,data);
};
const header = fs.readFileSync(path.join(root,'include/wgpupixel.h'),'utf8').split('class WGPUPIXEL_API Commands {')[1].split('private:')[0];
const methods = [...header.matchAll(/void (\w+)\(([\s\S]*?)\);/g)];
const required = new Set(methods.map(([, name, args]) => methods.filter(m=>m[1]===name).length > 1 ? `${name}:${args.match(/\b(Image|Mask)\b/)[1]}` : name));
const covered = new Set(examples.flatMap(item=>item.covers));
const missing = [...required].filter(name=>!covered.has(name));
if (missing.length) throw Error('Add examples for: '+missing.join(', '));
const ids = new Set();
for (const item of examples) {
  if (!/^[a-z][a-z0-9_]*$/.test(item.id) || ids.has(item.id)) throw Error('Invalid/duplicate example ID: '+item.id);
  ids.add(item.id);
  if (!item.title || !item.description || !sourceOf(item).trim() || !operationOf(item).trim()) throw Error('Incomplete example: '+item.id);
  for (const op of item.covers.filter(op=>required.has(op))) {
    if (!new RegExp(`\\.\\s*${op.split(':')[0]}\\s*\\(`).test(sourceOf(item))) throw Error(`${item.id} does not call ${op}`);
  }
}
// The generated pages: GPU operations by group, then complete programs.
const groups = {
  Create: 'Generate pixels: fills, patterns, shapes and noise.',
  Color: 'Point operations on linear colour.',
  Adjustments: 'Photoshop-style adjustments: levels, curves, LUTs and colour grading.',
  Filters: 'Neighbourhood filters: blurs, sharpening, noise reduction and morphology.',
  Effects: 'Stylised effects built on filters.',
  Transform: 'Resampling and geometry for images and masks.',
  Select: 'Build and refine selections, which are masks.',
  Compose: 'Blend layers: modes, layer masks, alpha lock, Blend If and clipping groups.',
  Paint: 'The brush engine and the tools built on it.',
  Analyze: 'Histograms, statistics and eyedropper sampling.',
};
const PROGRAMS = 'Use the library';
for (const item of examples) {
  if (item.group !== PROGRAMS && !(item.group in groups)) throw Error(`${item.id}: unknown group ${item.group}`);
}
const entry = item => [`### ${item.title}`, '', item.description, '',
  '```' + (item.language ?? 'cpp'), operationOf(item).trim(), '```',
  ...(item.body ? ['', `![${item.title}](images/examples/${item.id}.png)`] : []), ''];
const generated = '<!-- Generated by node tools/examples.mjs --docs from examples/examples.js; do not edit. -->';
const pages = {
  'operations.md': [
    '# Operations', '', generated, '',
    'Every GPU operation, with the result the GPU rendered from the code shown. Each snippet runs',
    'inside `ctx.run_and_wait([&](Commands& cmd) { ... })` on a 320×200 `image` which, unless the',
    'operation creates the pixels, starts as a gradient with two marks. The ranges and units of every',
    'option are documented in the public headers, in [`include/`](../include/).', '',
    ...Object.entries(groups).flatMap(([group, about]) => [`## ${group}`, '', about, '',
      ...examples.filter(item => item.group === group).flatMap(entry)]),
  ],
  'programs.md': [
    '# Programs', '', generated, '',
    'Complete programs for what happens around the operations: moving pixels in and out, masks,',
    'files, lifetime, memory, typography and putting an image on screen.', '',
    ...examples.filter(item => item.group === PROGRAMS).flatMap(entry),
  ],
};
const rendered = Object.fromEntries(Object.entries(pages).map(([name, lines]) =>
  [name, lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n']));

const [mode='--check', argument] = process.argv.slice(2);
if (mode==='--emit') {
  if (!argument) throw Error('Usage: node tools/examples.mjs --emit build/examples');
  const output=path.resolve(argument); fs.mkdirSync(output,{recursive:true});
  const cmake=['cmake_minimum_required(VERSION 3.25)','project(examples LANGUAGES CXX)',
    'find_package(wgpupixel CONFIG REQUIRED COMPONENTS core OPTIONAL_COMPONENTS text)',
    'set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")'];
  for (const item of examples.filter(item=>!item.language)) {
    write(path.join(output,item.id+'.cpp'),sourceOf(item));
    if (item.text) cmake.push('if(TARGET wgpupixel::text)');
    cmake.push(`add_executable(example_${item.id} ${item.id}.cpp)`,
      `target_link_libraries(example_${item.id} PRIVATE wgpupixel::wgpupixel${item.text?' wgpupixel::text':''})`);
    if (item.text) cmake.push('endif()');
  }
  write(path.join(output,'CMakeLists.txt'),cmake.join('\n')+'\n');
  console.log(`Emitted ${examples.filter(item=>!item.language).length} programs to ${output}`);
} else if (mode==='--render') {
  if (!argument) throw Error('Usage: node tools/examples.mjs --render build/examples/bin');
  const binaries=path.resolve(argument), manifest={_implementation: implementationHash()}; fs.mkdirSync(images,{recursive:true});
  for (const item of examples.filter(item=>item.body)) {
    const work=path.join(root,'build/example-output',item.id); fs.mkdirSync(work,{recursive:true});
    fs.rmSync(path.join(work,'output.png'),{force:true});
    const run=spawnSync(path.join(binaries,'example_'+item.id+(process.platform==='win32'?'.exe':'')),[],{cwd:work,encoding:'utf8',timeout:30000});
    if(run.error || run.status!==0) throw Error(`${item.id}: ${run.error ?? run.stderr}`);
    fs.copyFileSync(path.join(work,'output.png'),path.join(images,item.id+'.png'));
    manifest[item.id]=hash(item);
  }
  if (manifest._implementation !== implementationHash()) throw Error('Library inputs changed during rendering; rebuild and render again.');
  fs.writeFileSync(path.join(images,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');
  console.log(`Rendered ${Object.keys(manifest).length - 1} actual GPU results.`);
} else if (mode==='--docs') {
  for (const [name, text] of Object.entries(rendered)) write(path.join(docs, name), text);
  console.log(`Wrote ${Object.keys(rendered).map(name => 'docs/' + name).join(' and ')}.`);
} else if (mode==='--check') {
  for (const [name, text] of Object.entries(rendered)) {
    const file = path.join(docs, name);
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== text) throw Error(`Stale docs/${name}; run node tools/examples.mjs --docs.`);
  }
  const manifest=JSON.parse(fs.readFileSync(path.join(images,'manifest.json'),'utf8'));
  if (manifest._implementation !== implementationHash()) throw Error('Stale previews: library/build inputs changed; rebuild the SDK and render the examples again.');
  for (const item of examples.filter(item=>item.body)) {
    if (manifest[item.id]!==hash(item)) throw Error(`Stale preview for ${item.id}; emit, compile and render the examples.`);
    const png=fs.readFileSync(path.join(images,item.id+'.png'));
    if(png.subarray(0,8).toString('hex')!=='89504e470d0a1a0a') throw Error('Invalid preview: '+item.id);
  }
  console.log(`${examples.length} examples cover all ${required.size} GPU operation signatures; previews and generated docs are current.`);
} else throw Error('Choose --check, --docs, --emit or --render.');
