set(_shader_dir "${CMAKE_CURRENT_SOURCE_DIR}/src/shaders")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_shader_dir}/parameters.wgsl")
file(READ "${_shader_dir}/parameters.wgsl" _parameters)
set(_shader_code "#include \"kernels.h\"\nnamespace wgpupixel::detail {\n")

# Kernels describe themselves with leading "//! " directive lines, so adding a
# kernel never edits this file:
#   //! include <helper>...        append src/shaders/<helper>.wgsl
#   //! coverage generated|offset|kernel|none
#       generated (default): wrap apply_operation with the shared mask entry
#       offset: as generated, for kernels placing a source at params.offsets.xy
#       kernel: the kernel calls operation_coverage(index) itself
#       none: no masked pipeline
#   //! entry region|none            region (default) appends the shared dispatch entry
# Declaring @binding(7) opts into the variable-length data channel (parameters.wgsl).
set(_registry "${CMAKE_CURRENT_SOURCE_DIR}/src/kernel_list.inc")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_registry}")
file(STRINGS "${_registry}" _entries REGEX "^WGPUPIXEL_KERNEL")
set(_names "")
foreach(_entry IN LISTS _entries)
    string(REGEX REPLACE "WGPUPIXEL_KERNEL\\(([^)]+)\\)" "\\1" _name "${_entry}")
    list(APPEND _names "${_name}")
endforeach()
list(APPEND _names present)
foreach(_name IN LISTS _names)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_shader_dir}/${_name}.wgsl")
    file(READ "${_shader_dir}/${_name}.wgsl" _source)
    set(_coverage generated)
    set(_entry_mode region)
    string(REGEX MATCHALL "//![^\n]*" _directives "${_source}")
    foreach(_directive IN LISTS _directives)
        string(REGEX REPLACE "^//![ \t]*" "" _directive "${_directive}")
        string(REGEX REPLACE "[ \t]+" ";" _words "${_directive}")
        list(POP_FRONT _words _key)
        if(_key STREQUAL "include")
            foreach(_helper IN LISTS _words)
                set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_shader_dir}/${_helper}.wgsl")
                file(READ "${_shader_dir}/${_helper}.wgsl" _helper_source)
                string(APPEND _source "\n${_helper_source}")
            endforeach()
        elseif(_key STREQUAL "coverage" AND _words MATCHES "^(generated|offset|kernel|none)$")
            set(_coverage "${_words}")
        elseif(_key STREQUAL "entry" AND _words MATCHES "^(region|none)$")
            set(_entry_mode "${_words}")
        else()
            message(FATAL_ERROR "Unknown directive in shader ${_name}: //! ${_directive}")
        endif()
    endforeach()
    string(FIND "${_parameters}${_source}" ")wgsl\"" _delimiter)
    if(NOT _delimiter EQUAL -1)
        message(FATAL_ERROR "Reserved C++ string delimiter in shader ${_name}")
    endif()
    set(_data false)
    if(_source MATCHES "@binding\\(7\\)")
        set(_data true)
    endif()
    string(REPLACE "blur_" "gaussian_blur." _label "${_name}")
    set(_masked ", \"\"")
    if(_coverage MATCHES "^(generated|offset)$")
        set(_masked "${_source}")
        set(target pixels)
        set(target_x x)
        set(target_y y)
        if(_source MATCHES "var<storage, read_write> destination:")
            set(target destination)
            set(target_x z)
            set(target_y w)
        endif()
        set(dispatch_x ${target_x})
        set(dispatch_y ${target_y})
        set(coordinates "let x = id.x; let y = id.y;")
        if(_coverage STREQUAL "offset")
            set(dispatch_x x)
            set(dispatch_y y)
            set(coordinates "let x = destination_coordinate(id.x, params.offsets.x, params.dimensions.z); let y = destination_coordinate(id.y, params.offsets.y, params.dimensions.w);")
        endif()
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_shader_dir}/masked_entry.wgsl.in")
        file(READ "${_shader_dir}/masked_entry.wgsl.in" _entry_template)
        string(CONFIGURE "${_entry_template}" _entry @ONLY)
        set(_masked ", R\"wgsl(${_parameters}${_masked}\n${_entry})wgsl\"")
    endif()
    if(_entry_mode STREQUAL "region")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_shader_dir}/region_entry.wgsl")
        file(READ "${_shader_dir}/region_entry.wgsl" _entry)
        string(APPEND _source "\n${_entry}")
    endif()
    if(_coverage STREQUAL "kernel")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_shader_dir}/operation_coverage.wgsl")
        file(READ "${_shader_dir}/operation_coverage.wgsl" _coverage_source)
        set(_masked ", R\"wgsl(${_parameters}${_source}\n${_coverage_source})wgsl\"")
        string(APPEND _source "\nfn operation_coverage(index: u32) -> f32 { return 1.0; }\n")
    endif()
    string(APPEND _shader_code
        "Shader ${_name}_shader() noexcept {\n"
        "    return {\"${_label}\", R\"wgsl(${_parameters}${_source})wgsl\"${_masked}, ${_data}};\n}\n")
endforeach()

string(APPEND _shader_code "}\n")
file(CONFIGURE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/shaders.cpp" CONTENT "${_shader_code}" @ONLY)
